
export const parseStateComplianceData = async () => {
  // For now, return hardcoded data for CA and AL since we're having Excel parsing issues
  return {
    'CA': {
      overview: `<p>Homeschooling in California is a legally recognized educational option, but it comes with specific regulations and compliance requirements that parents must follow. In general, California law requires that all children between the ages of 6 and 18 be enrolled in a full-time public or private school, or receive instruction that is "at least equivalent" to what is taught in public schools. For homeschooling families, this typically involves choosing one of a few recognized avenues for legally providing home-based education.</p>`,
      legalAvenues: `<p><strong>1. Establishing a Private Home-Based School:</strong> Parents may file a Private School Affidavit (PSA) annually with the California Department of Education (CDE). By doing so, the home becomes a private school, and the parent (or another qualified person) serves as the instructor. Although the state does not require a formal teaching credential for parents when homeschooling through the private school option, it does expect that the instructor be "capable of teaching." Parents must offer instruction in the same branches of study required in public schools (e.g., English, mathematics, social sciences, science, fine arts, health, and physical education) and keep attendance records as well as other basic student records.</p>
<p><strong>2. Private School Satellite Program (PSP):</strong> Another pathway is to enroll the child in a private school satellite program. This option allows families to join a private school that oversees the homeschooling process and often provides curriculum guidance and record-keeping services. The private school satellite program files the PSA, so parents typically do not need to do so themselves. This arrangement often offers more support than operating an independent private home-based school, yet still provides substantial flexibility in daily instruction.</p>
<p><strong>3. Public Charter Schools or Independent Study Programs:</strong> California has a robust network of charter schools and independent study programs that cater specifically to homeschooling families. Parents who choose this route can work with a credentialed teacher provided by the charter school to develop an individualized learning plan for their child. While these programs allow for a high degree of flexibility in curriculum choices and scheduling, they may also require periodic check-ins or portfolio reviews to ensure that students meet state academic standards.</p>`,
      recordKeeping: `<p>Regardless of the chosen homeschooling route, maintaining thorough records is a key aspect of compliance. When families file a Private School Affidavit, they must keep attendance records, immunization records (or exemption documentation), and examples of student work. While the state does not routinely inspect these records, parents should be prepared to present them if necessary (for instance, if questions of truancy arise). Public charter schools and independent study programs typically have their own documentation requirements, which may include monthly progress reports or regular meetings with an assigned teacher.</p>`,
      curriculum: `<p>California does not mandate a specific curriculum for private home-based schools, so parents are free to choose instructional materials that align with their educational philosophy and goals. However, the law does require that home-based private schools cover the main subject areas offered in public schools. This includes instruction in English, mathematics, social sciences, science, health, and fine arts. Families are also encouraged to include physical education activities and any additional learning opportunities that bolster a well-rounded education.</p>`,
      funding: `<p>There are currently no direct state funding opportunities for homeschooling available.</p>`
    },
    'AL': {
      overview: `<p>Homeschooling is a well-established education option in Alabama. Estimates suggest that approximately <strong>30,000 families</strong> in Alabama homeschool, often through church-related or private school "cover" programs​. Public sentiment toward homeschooling is generally positive, with strong support networks (especially among faith-based communities) and a legal framework that affirms parental choice in education. In fact, Alabama law explicitly <strong>recognizes the right of parents to choose</strong> their child's educational method, <a target="_blank" rel="noopener noreferrer nofollow" href="https://law.justia.com/codes/alabama/title-16/chapter-1/section-16-1-11-2/#:~:text=Schools%20law,of%20his%20or%20her%20child"><span style="color: rgb(17, 85, 204)">stating</span></a> that <em>"a parent or guardian shall have the right to select the type school or method of...choice for the K-12 education of his or her child"</em>​. Alabama does not have a standalone homeschooling statute; instead, home education is conducted under the provisions for non-public schooling. This means families must <strong>comply with one of three legal avenues</strong> to meet compulsory attendance requirements: enrolling in a church school, operating as (or enrolling in) a private school, or using a certified private tutor. Overall, Alabama's homeschooling landscape is characterized by <strong>broad freedom with minimal state oversight</strong>, as long as basic enrollment and attendance rules are followed.</p>`,
      legalAvenues: `<p>Alabama law provides <strong>three legal pathways</strong> for home education, since there is no specific "homeschool" law​. Parents can choose the option that best fits their situation, but <strong>must register or notify authorities</strong> under the chosen category. Below are the avenues and their key requirements:</p>
<ul>
    <li><p><strong>Church School Option</strong> – Many Alabama families homeschool by enrolling their child in a <em>church school</em> (often called a "cover school"). Alabama defines a church school as a school offering K–12 instruction (including home programs) that is operated as a ministry of a local church or religious group​.</p></li>
    <li><p><strong>Private School Option</strong> – Alabama law also allows homeschooling under the guise of a <strong>private school</strong>. In practice, this can mean either enrolling in an existing private school that offers home-based programs or <strong>establishing your own private school</strong> in your home.</p></li>
    <li><p><strong>Private Tutor Option</strong> – The third option is to hire (or act as) a <strong>private tutor</strong> for the child. This option is more stringent and is less commonly used, since it requires the teaching parent or tutor to hold an Alabama teacher <em>certification</em>.</p></li>
</ul>`,
      recordKeeping: `<p><strong>Enrollment and Attendance Records:</strong> Alabama law places responsibility on homeschool families (and the schools or tutors they operate under) to keep basic educational records. Under the <strong>church school</strong> or <strong>private school</strong> options, parents should maintain <strong>attendance records</strong> for each homeschooled child and ensure those records are available if ever requested.</p>`,
      curriculum: `<p><strong>Subjects and Instructional Time:</strong> Alabama sets <strong>very few curricular mandates</strong> on homeschoolers who are enrolled in church schools or private schools. Neither the church-school option nor the private-school option specifies required subjects or a minimum number of hours of instruction in the home program.</p>`,
      funding: `<p>Alabama has a few programs that provide <strong>financial assistance or tax benefits</strong> related to K–12 education, although their applicability to homeschoolers varies. According to EdChoice, in recent years Alabama has expanded school choice funding through <strong>scholarships and Education Savings Accounts (ESAs)</strong> that some homeschooling families may access​.</p>`
    }
  };
}; 